### ISSUE TITLE
KeyError: 'dhl_de_username'  on installation with 3.6

### ISSUE THREAD

**Issue by oxidworks** [fulfilio/trytond-shipping-dhl-de#9]
Thank you very much for that module. I tried it on Tryton 3.4 and 3.6 but I always get an error when I try to create an new carrier:

```
ERROR:tryton.common.common:Traceback (most recent call last):
  File "/home/johannes/.virtualenvs/bugs/tryton/tryton/gui/window/form.py", line 336, in sig_new
    self.screen.new()
  File "/home/johannes/.virtualenvs/bugs/tryton/tryton/gui/window/view_form/screen/screen.py", line 438, in new
    self.switch_view('form')
  File "/home/johannes/.virtualenvs/bugs/tryton/tryton/gui/window/view_form/screen/screen.py", line 368, in switch_view
    self.load_view_to_load()
  File "/home/johannes/.virtualenvs/bugs/tryton/tryton/gui/window/view_form/screen/screen.py", line 389, in load_view_to_load
    self.add_view_id(view_id, view_type)
  File "/home/johannes/.virtualenvs/bugs/tryton/tryton/gui/window/view_form/screen/screen.py", line 402, in add_view_id
    return self.add_view(view)
  File "/home/johannes/.virtualenvs/bugs/tryton/tryton/gui/window/view_form/screen/screen.py", line 427, in add_view
    view = View.parse(self, xml_dom, view.get('field_childs'))
  File "/home/johannes/.virtualenvs/bugs/tryton/tryton/gui/window/view_form/view/__init__.py", line 49, in parse
    return ViewForm(screen, root)
  File "/home/johannes/.virtualenvs/bugs/tryton/tryton/gui/window/view_form/view/form.py", line 107, in __init__
    container = self.parse(xml)
  File "/home/johannes/.virtualenvs/bugs/tryton/tryton/gui/window/view_form/view/form.py", line 142, in parse
    parser(node, container, node_attrs)
  File "/home/johannes/.virtualenvs/bugs/tryton/tryton/gui/window/view_form/view/form.py", line 301, in _parse_group
    group = self.parse(node)
  File "/home/johannes/.virtualenvs/bugs/tryton/tryton/gui/window/view_form/view/form.py", line 142, in parse
    parser(node, container, node_attrs)
  File "/home/johannes/.virtualenvs/bugs/tryton/tryton/gui/window/view_form/view/form.py", line 170, in _parse_label
    field = self.screen.group.fields[attributes['name']]
KeyError: 'dhl_de_username'

'dhl_de_username'
```

**Comment by oxidworks** [comment]
I named the module folder wrong, that was the problem.Sorry
